"""Metric leaderboards — delegates to v2 (PIL logos + 200 DPI)."""

from aws_football.bsq_leaderboards_v2 import (
    ALL_METRIC_COLUMNS,
    AESTHETICS,
    BAR_RECT,
    FIG_WIDTH_IN,
    LOGO_RECT,
    NAME_RECT,
    OUTPUT_DPI,
    TEAM_LOGO_FILES,
    display_leaderboard_image,
    display_metric_leaderboards,
    leaderboard_png_bytes,
    load_leaderboard_shots,
    logo_path_for_team,
    matplotlib_metric_leaderboard,
    notebook_dark_style_html,
    player_metric_leaderboard,
    plotly_dark_leaderboard,
    plotly_metric_leaderboard,
    render_leaderboard_image,
    resolve_logo_dir,
    save_leaderboard_image,
    short_player_name,
)

__all__ = [
    "ALL_METRIC_COLUMNS",
    "AESTHETICS",
    "BAR_RECT",
    "FIG_WIDTH_IN",
    "LOGO_RECT",
    "NAME_RECT",
    "OUTPUT_DPI",
    "TEAM_LOGO_FILES",
    "display_leaderboard_image",
    "display_metric_leaderboards",
    "leaderboard_png_bytes",
    "load_leaderboard_shots",
    "logo_path_for_team",
    "matplotlib_metric_leaderboard",
    "notebook_dark_style_html",
    "player_metric_leaderboard",
    "plotly_dark_leaderboard",
    "plotly_metric_leaderboard",
    "render_leaderboard_image",
    "resolve_logo_dir",
    "save_leaderboard_image",
    "short_player_name",
]
